# Generated by Django 5.2.9 on 2026-03-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_topic_section_post_topics_group_topic_section_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics_group',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/imagenes/'),
        ),
        migrations.AlterField(
            model_name='topics_group',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
