# Generated by Django 5.2.9 on 2026-03-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_name_topics_group_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics_group',
            name='categoria',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
