# Generated by Django 5.2.9 on 2026-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_topics_group_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_group',
            name='post',
            field=models.ManyToManyField(blank=True, to='catalog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
