# Generated by Django 5.2.9 on 2026-03-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_topics_group_post_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics_group',
            old_name='post',
            new_name='posts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.topics_group'),
        ),
    ]
