# Generated by Django 5.2.9 on 2026-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_post_topics_group_posts_remove_post_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2005),
            preserve_default=False,
        ),
    ]
