# Generated by Django 5.2.9 on 2026-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_topics_group_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics_group',
            name='created_at',
        ),
    ]
